### ISSUE TITLE
Error on the anat_selectfiles node (SOLVED)

### ISSUE THREAD

**Issue by The-Archon-AI** [CoBrALab/RABIES#107]
**Describe the bug**
Whenever I try to run RABIES I run into the above error. 

**Attach log file**
https://drive.google.com/drive/folders/12Ub1OBGcmpOKzO71DBYtDZe1OwLhRzQE?usp=sharing

**Attach QC_report**
https://drive.google.com/file/d/1pak5phGwbO0YxKOapgyP2K_caehACrhR/view?usp=sharing

I am running RABIES through a singularity container on Linux. 

Any help with this issue will be appreciated.

**Comment by gdevenyi** [comment]
Hi.

Please do not ignore the issue template.

Provide the following information in the format requested:

**Describe the bug**
A clear and concise description of what the bug is.

**Describe RABIES call**
Include a copy of the command call you executed from the terminal, and any additional information that could be relevant to your execution.

**Attach log file**
Attach to your issue the .log files present in the output folder. (e.g. rabies_out/rabies_preprocess.log)

**Attach QC_report**
Attach to your issue the QC_report folder present in the output folder. If QC_report is too large, mention that it couldn't be shared, and if possible, provide an alternative access to the files.

**Additional context**
Add any other context about the problem here.

**Comment by gdevenyi** [comment]
Please provide all of the information requested from the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**Describe RABIES call**
Include a copy of the command call you executed from the terminal, and any additional information that could be relevant to your execution.

**Comment by The-Archon-AI** [comment]
Describe the bug
After running for about an hour (locally) RABIES stops at the anat_selectfiles node, then the terminal displays a "RABIES failed: Workflow did not execute cleanly" error message. 

Describe RABIES call
`singularity run -B /home/diegoe/Documents/MRI:/nii_inputs:ro \
-B /home/diegoe/Documents/preproc:/rabies_out \
/root/singularity/rabies.sif preprocess /nii_inputs /rabies_out \`

**Comment by Gab-D-G** [comment]
I believe the problem arises because you have a 'run-' specification in your anatomical image, but the software expects only 1 anatomical scan to be present per session and providing a run specification leads to your error. In the upcoming updates I will make sure this error doesn't arise, but in the meantime if you want to make it work with your current version, just remove the 'run-01' from your anatomical images. Let me know if this fixes your issue.

**Comment by The-Archon-AI** [comment]
It worked really well! Even better with the new update, however, a different issue came up. I'll let you know if I am unable to fix it
