### ISSUE TITLE
Main workflow not taking no_stc? 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#67]
https://github.com/CoBrALab/RABIES/blob/3a3db2222aaf7a0d306faf621453e6a4a0e00d4b/rabies/run_main.py#L239

It seems from this line that the no_stc option is only taken into consideration in the BOLD-only pipeline. 
Can you confirm?

**Comment by grandjeanlab** [comment]
also, follow-up: 
1. Did you check STC is done in the AP axis? In human, most common acquisition is along SI. 
Some weirdos (I mean it kindly) acquire rodent either LR or SI, but that is very rare. 
2. does one need to specify `--no_STC True` or is `--no_STC` without additional arguement sufficient? I couldn't tell from code, but `rabies -h` indicates default for no_STC is false, so it got me confused.

**Comment by Gab-D-G** [comment]
I comfirm that STC is taken in consideration in the main pipeline as well (see apply_STC in the inputs): https://github.com/CoBrALab/RABIES/blob/3a3db2222aaf7a0d306faf621453e6a4a0e00d4b/rabies/run_main.py#L239-L242

The option --no_STC means ignoring STC. If the --no_STC flag is specified, the STC step will be skipped. I noticed that the default in the rabies help is indeed confusing, since by default the output is true to run the STC step in the workflow, and --no_STC sets this to False. I will be changing this so that the --no_STC is False by default, and selecting this options turns is to True to make it more clear.

Concerning the orientation of the correction, I'll need to investigate it in more details. I had fixed recently inconsistencies in image orientation but I didn't check whether it aligns properly with AFNI's STC.

**Comment by gdevenyi** [comment]
Here's some code to allow argparse to have a --STC, --no_STC combined option:
https://github.com/CoBrALab/twolevel_ants_dbm/blob/master/twolevel_dbm.py#L660-L671

**Comment by Gab-D-G** [comment]
The previous versions were indeed applying STC on the wrong axis. AFNI's 3dTshift only applies STC in the z axis, which corresponds to the S-I axis. The script has been modified to apply the correction in the A-P axis, which should be most common in mice.
